services:
  helloworld:
    image: helloworld
    build: ./helloworld
    ports:
      - 8080:8080
    volumes:
      - ~/.aws-lambda-rie:/aws-lambda
    entrypoint:
      - /aws-lambda/aws-lambda-rie
      - /usr/local/bin/python
      - -m
      - awslambdaric
    command:
      - app.lambda_handler
